- name: Create an nginx conf volume
  docker_volume:
    name: "{{ nginx_volume }}"

- name: copy nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: "{{ docker_volume_path }}{{ nginx_volume }}/_data/nginx.conf"

- name: Pull nginx image
  docker_image:
    name: "{{ nginx_image }}"

- name: Create nginx container as reverse proxy for ipm
  docker_container:
    name: "{{ nginx_hostname }}"
    recreate: yes
    image: "{{ nginx_image }}"
    user: "{{ nginx_user }}"
    volumes:
      - "{{ nginx_volume }}:/etc/nginx/"
    ports:
      - "80:80/tcp"
    networks:
      - name: "{{ docker_network_name }}"
