- name: Create an nginx conf volume
  docker_volume:
    name: "{{ nginx_volume }}"

- name: copy nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: "{{ docker_volume_path }}{{ nginx_volume }}/_data/nginx.conf"

- name: copy htaccess
  template:
    src: templates/htaccess.j2
    dest: "{{ docker_volume_path }}{{ nginx_volume }}/_data/.htpasswd"

- name: Remove old nginx image
  docker_image:
    name: "{{ nginx_image }}"
    state: absent
    force: yes


- name: Pull nginx image
  docker_image:
    name: "{{ nginx_image }}"
    force: yes

- name: copy systemd service file
  template:
    src: templates/nginx.systemd.j2
    dest: "{{ systemd_dir }}/{{ nginx_hostname }}.service"
  notify:
    - reload systemd

- name: Create nginx container as reverse proxy for ipm
  docker_container:
    name: "{{ nginx_hostname }}"
    recreate: yes
    image: "{{ nginx_image }}"
    volumes:
      - "{{ nginx_volume }}:/etc/nginx/"
    ports:
      - "80:80/tcp"
    networks:
      - name: "{{ docker_network_name }}"

- name: flush handlers
  meta: flush_handlers

- name: ensure nginx is started and enabled in systemd
  systemd:
    name: "{{ nginx_hostname }}.service"
    state: started
    enabled: yes
