- name: Create an nginx conf volume
  docker_volume:
    name: "{{ nelson_volume }}"

- name: Pull Nelson image
  docker_image:
    name: "{{ nelson_image }}"

- name: copy config.ini
  template:
    src: templates/config.ini.j2
    dest: /var/lib/docker/volumes/{{ nelson_volume }}/_data/config.ini
