- name: Create an nginx conf volume
  docker_volume:
    name: "{{ nginx_volume }}"

- name: copy nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /var/lib/docker/volumes/{{ nginx_volume }}/_data/nginx.conf

- name: Pull nginx image
  docker_image:
    name: "{{ nginx_image }}"
