- name: Create IRI container
  docker_container:
    name: "{{ docker_name_prefix }}iri"
    recreate: yes
    image: "{{ docker_image_iri }}"
    volumes:
      - "{{ docker_name_prefix }}iri_data:/opt/iri/data"
    ports:
      - "14265:14265/tcp"
      - "14600:14600/udp"
      - "15600:15600/tcp"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      NEIGHBORS="{{ neighbors }}"

- name: Create IOTA Peermanager container
  docker_container:
    name: "{{ ipm_host }}"
    recreate: yes
    image: "{{ docker_image_ipm }}"
    volumes:
      - "{{ docker_name_prefix }}ipm:/home/ipm"
    ports:
      - "127.0.0.1:8888:8888/tcp"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      API_PORT=14265
      REFRESH=10s
      IOTA_HOST="{{ docker_name_prefix }}iri"

- name: Create nginx container as reverse proxy for ipm
  docker_container:
    name: "{{ docker_name_prefix }}_nginx"
    recreate: yes
    image: "{{ docker_image_nginx }}"
    volumes:
      - "{{ nginx_volume }}:/etc/nginx/"
    ports:
      - "80:80/tcp"
    networks:
      - name: "{{ docker_network_name }}"
