- name: Create IRI container
  docker_container:
    name: "{{ iri_hostname }}"
    recreate: yes
    image: "{{ iri_image }}"
    volumes:
      - "{{ docker_name_prefix }}iri_data:/opt/iri/data"
    ports:
      - "14265:14265/tcp"
      - "14600:14600/udp"
      - "15600:15600/tcp"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      NEIGHBORS="{{ iri_neighbors }}"

- name: Create IOTA Peermanager container
  docker_container:
    name: "{{ ipm_host }}"
    recreate: yes
    image: "{{ ipm_image }}"
    volumes:
      - "{{ docker_name_prefix }}ipm:/home/ipm"
    ports:
      - "127.0.0.1:8888:8888/tcp"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      API_PORT=14265
      REFRESH=10s
      iri_hostname="{{ iri_hostname }}"

- name: Create nginx container as reverse proxy for ipm
  docker_container:
    name: "{{ nginx_host }}"
    recreate: yes
    image: "{{ nginx_image }}"
    volumes:
      - "{{ nginx_volume }}:/etc/nginx/"
    ports:
      - "80:80/tcp"
    networks:
      - name: "{{ docker_network_name }}"

- name: Create nelson container for managing peers
  docker_container:
    name: "{{ nelson_host }}"
    recreate: yes
    image: "{{ nelson_image }}"
    volumes:
      - "{{ nelson_volume }}:/etc/nelson"
    ports:
      - "16600:16600"
      - "18600:18600"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      NELSON_CONFIG="{{ nelson_configdir }}/config.ini"
  tags:
    - restart_nelson
    - nelson
