- name: copy docker-compose.yml to remote host
  template:
    src: templates/docker-compose.yml.j2
    dest: /tmp/docker-compose.yml

- name: Run docker-compose stop
  shell: docker-compose -p {{ project_name }} stop
  args:
    chdir: /tmp/
  when: setupdb == "true"

- name: Download current Mainnet DB of IOTA
  get_url:
    url: http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz
    dest: /tmp/
  when: setupdb == "true" and skipdbdl != "true"

- name: Extract Tarball
  shell: tar xfz /tmp/IOTA.partners-mainnetdb.tar.gz -C /var/lib/docker/volumes/{{ project_name }}_iota_data/_data/mainnetdb/
  when: setupdb == "true"

- name: Change/Fix Ownership
  file:
    path: /var/lib/docker/volumes/{{ project_name }}_iota_data/_data/mainnetdb/
    owner: root
    group: root
    recurse: true

- name: Run docker-compose
  shell: docker-compose -p {{ project_name }} up -d
  args:
    chdir: /tmp/
