- name: Upgrade all packages (debian)
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Ensure depdencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - jq
    - ufw
    - lsof
    - curl
    - pv
    - python3-pip

- name: Check if a reboot is required (debian)
  stat:
    path: /var/run/reboot-required
  register: reboot_file
  check_mode: no

- name: Set reboot_required (debian)
  set_fact:
    reboot_required: true
  when: reboot_file.stat.exists
