- name: Download current Mainnet DB of IOTA
  get_url:
    url: "{{ iri_db_url }}"
    dest: /tmp/

- name: Extract Tarball
  shell: tar xfz /tmp/{{ iri_db_filename }} -C {{ iri_db_folder }}

- name: Change/Fix Ownership
  file:
    path: "{{ iri_db_folder }}"
    owner: "{{ iri_user }}"
    group: "{{ iri_group }}"
    recurse: true
