- name: Create docker network
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create an IRI data volume
  docker_volume:
    name: "{{ iri_data_volume }}"

- import_tasks: database.yml
  tags:
    - download_db

- name: Remove old IRI image
  docker_image:
    name: "{{ iri_image }}"
    state: absent
    force: yes

- name: Pull IRI image
  docker_image:
    name: "{{ iri_image }}"
    force: yes

- name: copy systemd service file
  template:
    src: templates/iri.systemd.j2
    dest: "{{ systemd_dir }}/{{ iri_hostname }}.service"
  notify:
    - reload systemd

- name: Create IRI container
  docker_container:
    name: "{{ iri_hostname }}"
    recreate: yes
    image: "{{ iri_image }}"
    volumes:
      - "{{ iri_data_volume }}:/opt/iri/data"
    ports:
    # WARNING: Do not expose iri_api_port to public! There is no limitation for API calls in place.
      - "127.0.0.1:{{ iri_api_port }}:14265/tcp"
      - "{{ iri_udp_port }}:14600/udp"
      - "{{ iri_tcp_port }}:15600/tcp"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      NEIGHBORS="{{ iri_neighbors }}"
      JAVA_OPTIONS="{{ iri_java_options }}"
      REMOTE_API_LIMIT=""

- name: flush handlers
  meta: flush_handlers

- name: ensure iri is started and enabled in systemd
  systemd:
    name: "{{ iri_hostname }}.service"
    state: started
    enabled: yes
