# Taken from https://github.com/nuriel77/iri-playbook/
- name: ensure firewalld started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: allow iri tcp port in firewall
  firewalld:
    port: "{{ iri_tcp_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes

- name: allow iri udp port in firewall
  firewalld:
    port: "{{ iri_udp_port }}/udp"
    permanent: true
    state: enabled
    immediate: yes
