- import_role:
    name: essentials

- import_tasks: ufw.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: iri_firewall

- import_tasks: firewalld.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: iri_firewall

- import_tasks: docker_iri.yml
